import { Inject, Injectable } from "@nestjs/common";
import type { RequestAuth } from "../auth/types";
import { PARTICIPANT_REPOSITORY } from "../constants/repository-tokens.constants";
import {
  ConflictError,
  NotFoundError,
  UniqueConstraintViolationError,
} from "../domain/errors";
import { utcNowStoredDate } from "../domain/time";
import type {
  CreateParticipantBody,
  UpdateParticipantBody,
} from "../dtos/participant";
import type { TripParticipant } from "../generated/prisma/client";
import type {
  IParticipantRepository,
  ParticipantUpdatePersistenceInput,
} from "../repositories/interfaces/IParticipantRepository";
import { RlsUnitOfWork } from "../repositories/rls-unit-of-work";

@Injectable()
export class ParticipantService {
  constructor(
    @Inject(PARTICIPANT_REPOSITORY)
    private readonly participantRepository: IParticipantRepository,
    private readonly rlsUnitOfWork: RlsUnitOfWork,
  ) {}

  /**
   * Adds a traveler as a participant of a trip.
   *
   * The invitation timestamp is generated by the service. When the initial
   * invitation status is already accepted or declined, respondedAt is also
   * initialized immediately.
   *
   * @param auth Verified authentication context.
   * @param tripId Trip identifier.
   * @param input Validated participant creation payload.
   * @returns The created Prisma TripParticipant.
   * @throws ConflictError When the traveler is already a participant.
   */
  async create(
    auth: RequestAuth,
    tripId: string,
    input: CreateParticipantBody,
  ): Promise<TripParticipant> {
    const now = utcNowStoredDate();

    try {
      return await this.rlsUnitOfWork.execute(auth, (transaction) =>
        this.participantRepository.create(transaction, {
          ...input,
          tripId,
          invitedAt: now,
          respondedAt:
            input.inviteStatus === "pending"
              ? null
              : now,
        }),
      );
    } catch (error) {
      if (error instanceof UniqueConstraintViolationError) {
        throw new ConflictError(
          "Traveler is already a trip participant",
        );
      }

      throw error;
    }
  }

  /**
   * Returns all participants belonging to a trip.
   *
   * @param auth Verified authentication context.
   * @param tripId Trip identifier.
   * @returns Prisma TripParticipant objects visible through RLS.
   */
  findAll(
    auth: RequestAuth,
    tripId: string,
  ): Promise<TripParticipant[]> {
    return this.rlsUnitOfWork.execute(auth, (transaction) =>
      this.participantRepository.findAll(
        transaction,
        tripId,
      ),
    );
  }

  /**
   * Returns one participant belonging to a trip.
   *
   * @param auth Verified authentication context.
   * @param tripId Trip identifier.
   * @param participantId Participant identifier.
   * @returns The matching Prisma TripParticipant.
   * @throws NotFoundError When the participant does not exist or is not visible.
   */
  findById(
    auth: RequestAuth,
    tripId: string,
    participantId: string,
  ): Promise<TripParticipant> {
    return this.rlsUnitOfWork.execute(auth, async (transaction) => {
      const participant = await this.participantRepository.findById(
        transaction,
        tripId,
        participantId,
      );

      if (participant === null) {
        throw new NotFoundError("Trip participant");
      }

      return participant;
    });
  }

  /**
   * Updates the mutable fields of a trip participant.
   *
   * Only explicitly provided values are forwarded to the repository.
   * Changing the invitation status also updates respondedAt: pending clears
   * the response timestamp, while accepted or declined sets it to now.
   *
   * @param auth Verified authentication context.
   * @param tripId Trip identifier.
   * @param participantId Participant identifier.
   * @param input Validated partial participant update payload.
   * @returns The updated Prisma TripParticipant.
   * @throws NotFoundError When the participant does not exist or is not visible.
   */
  update(
    auth: RequestAuth,
    tripId: string,
    participantId: string,
    input: UpdateParticipantBody,
  ): Promise<TripParticipant> {
    const persistenceInput: ParticipantUpdatePersistenceInput = {};

    if (input.role !== undefined) {
      persistenceInput.role = input.role;
    }

    if (input.inviteStatus !== undefined) {
      persistenceInput.inviteStatus = input.inviteStatus;
    }

    if (input.canViewDocuments !== undefined) {
      persistenceInput.canViewDocuments = input.canViewDocuments;
    }

    if (input.inviteStatus !== undefined) {
      persistenceInput.respondedAt =
        input.inviteStatus === "pending"
          ? null
          : utcNowStoredDate();
    }

    return this.rlsUnitOfWork.execute(auth, async (transaction) => {
      const participant = await this.participantRepository.update(
        transaction,
        tripId,
        participantId,
        persistenceInput,
      );

      if (participant === null) {
        throw new NotFoundError("Trip participant");
      }

      return participant;
    });
  }

  /**
   * Deletes a participant from a trip.
   *
   * @param auth Verified authentication context.
   * @param tripId Trip identifier.
   * @param participantId Participant identifier.
   * @throws NotFoundError When no matching participant could be deleted.
   */
  delete(
    auth: RequestAuth,
    tripId: string,
    participantId: string,
  ): Promise<void> {
    return this.rlsUnitOfWork.execute(auth, async (transaction) => {
      const deleted = await this.participantRepository.delete(
        transaction,
        tripId,
        participantId,
      );

      if (!deleted) {
        throw new NotFoundError("Trip participant");
      }
    });
  }
}