export const PROFILE_REPOSITORY = Symbol("PROFILE_REPOSITORY");
export const TRAVELER_REPOSITORY = Symbol("TRAVELER_REPOSITORY");
export const TRIP_REPOSITORY = Symbol("TRIP_REPOSITORY");
export const PARTICIPANT_REPOSITORY = Symbol("PARTICIPANT_REPOSITORY");
export const BOOKING_REPOSITORY = Symbol("BOOKING_REPOSITORY");
export const BOOKING_TRAVELER_REPOSITORY = Symbol(
  "BOOKING_TRAVELER_REPOSITORY",
);
export const LOCATION_REPOSITORY = Symbol("LOCATION_REPOSITORY");
export const IDENTITY_REPOSITORY = Symbol("IDENTITY_REPOSITORY");
